---

env:
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  sourceType: 'module'
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
extends:
  - standard
  - standard-with-typescript
  - standard-jsx
  - standard-react
rules:
  react/react-in-jsx-scope: off
